/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#E63946",
        secondary: "#FF6F61",
        background: "#FFFFFF",
        secondaryBackground: "#F5F5F5",
        highlightedBackground: "#FFD3D3",
        primaryText: "#333333",
        secondaryText: "#666666",
        disabledText: "#B0B0B0",
        primaryButtonBackground: "#E63946",
        primaryButtonText: "#FFFFFF",
        secondaryButtonBackground: "#FF6F61",
        secondaryButtonText: "#FFFFFF",
        linkColor: "#E63946",
        hoverLinkColor: "#D62839",
        errorColor: "#FF4C4C",
        successColor: "#4CAF50",
        borderColor: "#DDDDDD",

        darkPrimary: "#E63946",
        darkSecondary: "#FF6F61",
        darkBackground: "#121212",
        darkSecondaryBackground: "#1E1E1E",
        darkHighlightedBackground: "#2C2C2C",
        darkPrimaryText: "#FFFFFF",
        darkSecondaryText: "#CCCCCC",
        darkDisabledText: "#666666",
        darkPrimaryButtonBackground: "#E63946",
        darkPrimaryButtonText: "#FFFFFF",
        darkSecondaryButtonBackground: "#FF6F61",
        darkSecondaryButtonText: "#FFFFFF",
        darkLinkColor: "#E63946",
        darkHoverLinkColor: "#D62839",
        darkErrorColor: "#FF4C4C",
        darkSuccessColor: "#4CAF50",
        darkBorderColor: "#444444",
      },
    },
  },
  plugins: [],
};
