/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#E63946",
        secondary: "#FF6F61",
        background: "#FFFFFF",
        "secondary-background": "#F5F5F5",
        "highlighted-background": "#FFD3D3",
        "primary-text": "#333333",
        "secondary-text": "#666666",
        "disabled-text": "#B0B0B0",
        "primary-button-background": "#E63946",
        "primary-button-text": "#FFFFFF",
        "secondary-button-background": "#FF6F61",
        "secondary-button-text": "#FFFFFF",
        "link-color": "#E63946",
        "hover-link-color": "#D62839",
        "error-color": "#FF4C4C",
        "success-color": "#4CAF50",
        "border-color": "#DDDDDD",

        "dark-primary": "#E63946",
        "dark-secondary": "#FF6F61",
        "dark-background": "#121212",
        "dark-secondary-background": "#1E1E1E",
        "dark-highlighted-background": "#2C2C2C",
        "dark-primary-text": "#FFFFFF",
        "dark-secondary-text": "#CCCCCC",
        "dark-disabled-text": "#666666",
        "dark-primary-button-background": "#E63946",
        "dark-primary-button-text": "#FFFFFF",
        "dark-secondary-button-background": "#FF6F61",
        "dark-secondary-button-text": "#FFFFFF",
        "dark-link-color": "#E63946",
        "dark-hover-link-color": "#D62839",
        "dark-error-color": "#FF4C4C",
        "dark-success-color": "#4CAF50",
        "dark-border-color": "#444444",
      },
    },
  },
  plugins: [],
};
